name: Artifacts

on: push

jobs:
    # job1:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Create files
    #           run: |
    #             mkdir build
    #             echo "This is test build!!" > build/info.txt

    #         - name: upload the build folder
    #           uses: actions/upload-artifact@v7
    #           with:
    #             name: build-output
    #             path: build/


    job2:
        # needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: download artifacts
              uses: actions/download-artifact@v8
              with:
                name: build-output
                path: ./build

            - name: display the contents
              run: |
                ls -lart ./build
                cat ./build/info.txt

                