name: ouputs

on:
    workflow_dispatch

jobs:
    job1:
        runs-on: ubuntu-latest
        
        steps:
            - name: set a variable
              id: step1
              run: echo "msg=Itd from Step1 " >> $GITHUB_OUTPUT

            - name: get step1 variable
              run: echo "The out from step1 ===> ${{ steps.step1.outputs.msg }}"