name: Variables

on: 
    workflow_dispatch:
        inputs:
            environment:
                description: 'Run environment'
                required: true
                default: 'test'
                type: choice
                options:
                - dev
                - prod
                - test
            
            version:
                description: 'Application Version'
                required: true
                default: "v1.0.0"

env:
    TYPE_OF_APP: "1 Tire App"


jobs:
    show-the-variables:
        runs-on: ubuntu-latest
        steps:
            - name: Display Inputs
              run: |
                echo "Run Environment: ${{inputs.environment}}"
                echo "App Version: ${{inputs.version}}"


            - name: Environment Variable
              run: |
                echo "Environment: $TYPE_OF_APP"